development:
  adapter: postgresql
  encoding: unicode
  database: api_devbootcamp_com_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: api_devbootcamp_com_test
  pool: 5
